### ISSUE TITLE
Error initialising the database

### ISSUE THREAD

**Issue by adamshand** [iansinnott/prompta#5] opened 2023-07-25 23:49 UTC
Hi,

I've been using the Prompta macOS application for a few days and really liking it, thanks!

Yesterday I pasted in a good chunk of JS error message trying to solve a problem and Prompta crashed.  Since then, opening Prompta app has resulted in the below error message:

> There was an error initializing the database. Please try again.  If the problem persists, please report in on GitHub.sqlite3_open_v2.

![image](https://github.com/iansinnott/prompta/assets/130651/b63b38d7-51c2-45a1-8ad7-bb40e76ac932)

Deleting `~/Library/WebKit/com.prompta.dev` got rid of the error message, but Prompta still hangs forever on opening.

Deleting `~/Library/Caches/com.prompta.dev` and I had to enter my API key again but everything is working.

**Comment by iansinnott** [comment] 2023-07-26 14:27
Hey @adamshand , I'm seeing the same error although only in the PWA-installed version. I'm guessing you're getting this directly in the browser?

**Comment by iansinnott** [comment] 2023-07-26 14:28
eh, sorry, i see you're using the installed macos version. latest version?

**Comment by adamshand** [comment] 2023-07-27 00:10
Yes, I believe it's the latest version:  Version 1.1.0 (20230717.161342)

**Comment by adamshand** [comment] 2023-07-27 04:50
Just had it happen again when pasting JS code.

**Comment by adamshand** [comment] 2023-07-27 05:37
Just got it again on the web interface at chat.prompta.dev (5:37pm NZT if you want to look at logs).  Not JS code this time, just text.

**Comment by iansinnott** [comment] 2023-07-27 09:59
What browser? I'm wondering if this is safari related, since the desktop
build is equivalent

**Comment by iansinnott** [comment] 2023-07-27 10:00
ah i see. responded from email which didn't have the image

**Comment by iansinnott** [comment] 2023-07-27 10:03
I'm still not able to repro this. Tried in incognito Brave and the app seems to be working. There's definitely an issue, as i've seen it before too, but i don't currently have a way to reproduce the issue. 

any thoughts? it seems like you're running into this fairly often?

**Comment by iansinnott** [comment] 2023-07-27 16:43
I upgraded the database dependencies. This is where the wasm version of sqlite we use comes from. 

Not that this will resolve the problem, but you could try the latest version and see if it's any different: https://github.com/iansinnott/prompta/releases/tag/v1.1.1

**Comment by adamshand** [comment] 2023-07-27 22:07
Will upgrade and see how it goes, thanks!

No idea on reproducibility, seems pretty random, but often as chat logs get longer.  Could it have something to do with tokens running out?

If I spot a pattern or can reliably reproduce, will let you know!

**Comment by jdahlborg** [comment] 2023-08-30 11:59
Hello,

I encountered the following error just before the above mentioned problem while using the application:

> sqlite-api.js:866 Uncaught (in promise) Error: database disk image is malformed
    at check (sqlite-api.js:866:11)
    at Object.step (sqlite-api.js:699:14)
    at async _TX.statements (TX.ts:152:17)
check @ sqlite-api.js:866
(anonymous) @ sqlite-api.js:699
await in (anonymous) (async)
submit_handler_1 @ +page.svelte:332

This issue has happened multiple times but unfortunately I'm unable to reproduce it. I'll also try to spot a pattern!
I'm using chrome directly. Not PWA.

**Comment by iansinnott** [comment] 2023-11-02 08:51
In a separate project I ran into a similar issue, which lead me to this: https://github.com/vlcn-io/js/issues/31

Prompta uses wa-sqlite with fts5 or search and persistence.

**Comment by rhashimoto** [comment] 2023-11-02 21:36
@iansinnott  I think there are two different problems in this thread. The one with the stack trace and "Error: database disk image is malformed" could indeed be https://github.com/vlcn-io/js/issues/31 for which the underlying problems in wa-sqlite and SQLite were recently fixed.

The one that just says "sqlite3_open_v2" doesn't match up with the above bug. There is no known wa-sqlite problem that fails within sqlite3_open_v2() like that. When this occurs, it would be helpful to check the browser Dev Tools JavaScript console for error messages.

**Comment by iansinnott** [comment] 2023-11-03 07:19
Thanks for chiming in @rhashimoto. These may indeed be separate bugs, but when i've seen this pop up in the past they seem correlated. It usually goes like:

1. Disk image malformed error
2. (I restart the app)
3. open_v2 error, assumedly due to malformed database

The app code has not done a good job of surfacing full stack traces for users to post though, so I'm speculating. Looking forward to your recent fix getting merged into vlcn

**Comment by iansinnott** [comment] 2023-11-03 07:22
Anecdotally, I replaced the use of FTS5 with `LIKE '%query%'` in another app where I'm using vlcn, and so far have had zero issues. When using FTS5 the database would become malformed usually within hours of resetting it.

**Closed** 2023-11-29 06:04 UTC
